### ISSUE TITLE
~

### ISSUE THREAD

**Issue by qaz7791869** [TryA9ain/BypassAddUser_new#1]
~

**Comment by TryA9ain** [comment]
是的，我也注意到了，但那个时候忙于hw，后来再去看github已经下线了，那个腾讯管家图标的谷歌更新程序有点秀的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TryA9ain/BypassAddUser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月20日(星期二) 下午5:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[TryA9ain/BypassAddUser] 你上线了 (#1)





 
6小时前你问问题的地方，那个工具，自己放虚拟机里开网络监控查，注意windows/tmp目录
